### ISSUE TITLE
"Break Down" action screen dims and does not revert.

### ISSUE THREAD

**Issue by bushtail** [Xpazeman/tld-better-bases#2]
When breaking an object down, the screen dims as normal but does not reset the brightness of your screen. This is a temporary issue which fixed by performing a vanilla action - crafting, repairing, etc. but it took me a while to figure things out myself.
![image](https://user-images.githubusercontent.com/13682541/173437312-260c44f4-c941-4d01-a42f-69dc345eb43c.png)

**Comment by Xpazeman** [comment]
Haven't been able to reproduce, and probably comes from a conflict with other mod, as BetterBases doesn't modify the breaking down panel, it just adds the ability to breakdown things that normally can't be
