### ISSUE TITLE
An interactable calendar blocks a way in the Orca gasoline station in Milton

### ISSUE THREAD

**Issue by Lissimo** [Xpazeman/tld-better-bases#4]
In the Orca gasoline station in Milton is a calendar, which blocks the way to the tiny area behind the counter.
Nothing ordinary, but it should maybe mentioned. Deactivating the mod (if you want to keep the calendar) or destroying the calendar fixes this issue.

**Comment by SavalIje** [comment]
crouch

**Comment by Xpazeman** [comment]
Yes, some of the Hinterland geometry and colliders are more noticeable with the mod. Not much can be done about it except removing it or trying to get around by crouching.
