### ISSUE TITLE
Some other stuff, which would be nice to move

### ISSUE THREAD

**Issue by Lissimo** [Xpazeman/tld-better-bases#5]
I know that some stuff cannot be moved, which has certain limitations like interactability (Microwave or Radio). But would it be possible to move the following things:

1. Plant Pots
2. Paper (the small ones on the ground like the Paper Deco)
3. Paper Deco (like the calendar, which blocks the way in the Orca gas station)
4. Paint cans and pain can lids
5. Baskets
6. Computer, Screens, keyboars, mouses, Floppy discs
7. Pillows
8. Wheels
9. Curtains and curtain bars
10. Pictures (frames) and bulletin boards
11. Barrels?

**Comment by Lissimo** [comment]
Just want to add:
12. cartons (those mostly to find under beds, which lays on the ground)

And what I meant with "1. Paper" is the "Paper debris" and interesingly: stacked "Paper deco" (like the 'normal' stacked paper) is moveable, single "Paper deco" sheets are not moveable (put removeable of course).

**Comment by SavalIje** [comment]
agreed

**Comment by Xpazeman** [comment]
Thanks for the suggestions.

Moving paper debris won't be added as part of it isn't really an object and some others would conflict with items like stacked paper.

Also, objects that usually are put vertically on walls are tricky, so not a priority.

As for the rest of suggestions, I'll keep them in mind for future updates to the moveable object pool. I need to build the models for them so then can be moveable, as in vanilla those are static objects baked into the scene.
